sudo: required

language: cpp

compiler:
  - gcc
  - clang

services:
  - docker 

before_install:
  - docker pull ubuntu:16.04 

env:
  - TRAVIS_BRANCH="SFINAE"
   
script:
 - docker build --build-arg BRANCH=$TRAVIS_BRANCH .

 